"use client";

// =============================================================================
// isaacpaha.com — Tool Dashboard Client
// components/admin/tools/tool-dashboard-client.tsx
//
// Per-tool admin hub. Displays current tool data, engagement metrics,
// and clearly-labelled "under development" sections for each future
// dashboard module. Specific modules are planned per tool type:
//
//  AI tools        → Prompt editor, model config, token usage
//  Calculator/util → Config, formula editor
//  Tracker         → User data management, export
//  All tools       → Analytics, usage logs, settings, SEO
// =============================================================================

import React, { useState } from "react";
import {
  ArrowLeft, ExternalLink, Settings, BarChart2, 
  Sparkles, Database, Users,  Star, Lock, Globe,
  Zap, Eye, Copy, Check, 
  Construction,  Activity, ChevronRight,
  Edit2, Package, Cpu, Shield,
} from "lucide-react";
import Link from "next/link";

// ─── Types ────────────────────────────────────────────────────────────────────

type ToolStatus = "LIVE" | "BETA" | "COMING_SOON";

type Tool = {
  id:            string;
  title:         string;
  slug:          string;
  tagline:       string;
  description:   string;
  category:      string;
  status:        ToolStatus;
  emoji:         string;
  tags:          string;
  coverImage:    string | null;
  isFeatured:    boolean;
  isPremium:     boolean;
  isInteractive: boolean;
  componentKey:  string | null;
  viewCount:     number;
  useCount:      number;
  rating:        number;
  ratingCount:   number;
  createdAt:     Date;
  updatedAt:     Date;
  _count:        { usage: number };
};

type UsageLog = {
  id:        string;
  usedAt:    Date;
  userId:    string | null;
  sessionId: string | null;
};

interface Props {
  userId:    string;
  tool:      Tool;
  usageLogs: UsageLog[];
}

// ─── Config ───────────────────────────────────────────────────────────────────

const STATUS_CFG: Record<ToolStatus, { label: string; color: string; bg: string; dot: string }> = {
  LIVE:        { label: "Live",        color: "#059669", bg: "#d1fae5", dot: "#10b981" },
  BETA:        { label: "Beta",        color: "#d97706", bg: "#fef3c7", dot: "#f59e0b" },
  COMING_SOON: { label: "Coming Soon", color: "#6b7280", bg: "#f3f4f6", dot: "#9ca3af" },
};

const CATEGORY_CFG: Record<string, { emoji: string; color: string; bg: string }> = {
  AI:           { emoji: "🤖", color: "#f59e0b", bg: "#fef3c7" },
  Career:       { emoji: "💼", color: "#ec4899", bg: "#fce7f3" },
  Startup:      { emoji: "🚀", color: "#10b981", bg: "#d1fae5" },
  Education:    { emoji: "📚", color: "#8b5cf6", bg: "#ede9fe" },
  Productivity: { emoji: "⚡", color: "#14b8a6", bg: "#ccfbf1" },
  Writing:      { emoji: "✍️", color: "#3b82f6", bg: "#dbeafe" },
};

// Dashboard modules — defined per tool type; marked as planned until built
type ModuleStatus = "built" | "planned" | "partial";

type DashboardModule = {
  id:          string;
  label:       string;
  description: string;
  icon:        React.ElementType;
  status:      ModuleStatus;
  eta?:        string;
  forTypes?:   string[];  // tool categories / types this applies to
};

const MODULES: DashboardModule[] = [
  {
    id: "analytics",
    label: "Analytics & Traffic",
    description: "Page views, unique visitors, traffic sources, and conversion funnel from view → use.",
    icon: BarChart2,
    status: "planned",
    eta: "Phase 2",
  },
  {
    id: "usage-logs",
    label: "Usage Logs",
    description: "Every tool invocation — timestamps, anonymous vs authenticated, session replay.",
    icon: Activity,
    status: "planned",
    eta: "Phase 2",
  },
  {
    id: "ai-config",
    label: "AI Model Configuration",
    description: "Edit the system prompt, swap model, configure temperature, token limits, and test runs.",
    icon: Cpu,
    status: "planned",
    eta: "Phase 3",
    forTypes: ["AI", "Career", "Startup", "Education"],
  },
  {
    id: "prompt-editor",
    label: "Prompt Studio",
    description: "Version-controlled prompt editor with A/B testing, diff view, and rollback.",
    icon: Sparkles,
    status: "planned",
    eta: "Phase 3",
    forTypes: ["AI", "Career", "Startup", "Education"],
  },
  {
    id: "user-data",
    label: "User Data Management",
    description: "View, export, and manage data generated by authenticated users (saved states, histories).",
    icon: Database,
    status: "planned",
    eta: "Phase 3",
    forTypes: ["Career", "Productivity"],
  },
  {
    id: "ratings",
    label: "Ratings & Reviews",
    description: "Moderate user ratings, respond to reviews, flag abuse, and analyse sentiment.",
    icon: Star,
    status: "planned",
    eta: "Phase 2",
  },
  {
    id: "rate-limits",
    label: "Rate Limits & Access Control",
    description: "Configure per-user/anonymous rate limits, premium gating, and abuse detection.",
    icon: Shield,
    status: "planned",
    eta: "Phase 3",
  },
  {
    id: "seo",
    label: "SEO & Meta",
    description: "Edit meta title, description, OG image, and canonical URL for the tool's public page.",
    icon: Globe,
    status: "planned",
    eta: "Phase 2",
  },
  {
    id: "changelog",
    label: "Tool Changelog",
    description: "Document updates and improvements shown to users on the tool page.",
    icon: Package,
    status: "planned",
    eta: "Phase 2",
  },
  {
    id: "settings",
    label: "Tool Settings",
    description: "Toggle visibility, maintenance mode, premium flag, featured status, and component key.",
    icon: Settings,
    status: "planned",
    eta: "Phase 2",
  },
];

// ─── Utilities ────────────────────────────────────────────────────────────────

function parseTags(raw: string): string[] {
  try { return JSON.parse(raw); } catch { return []; }
}

function fmtDate(d: Date | string): string {
  return new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

// Build usage sparkline data (last 30 days → daily counts)
function buildDailyUsage(logs: UsageLog[]): { day: string; count: number }[] {
  const map: Record<string, number> = {};
  for (let i = 29; i >= 0; i--) {
    const d = new Date(Date.now() - i * 86400000);
    const k = d.toISOString().slice(0, 10);
    map[k] = 0;
  }
  for (const log of logs) {
    const k = new Date(log.usedAt).toISOString().slice(0, 10);
    if (k in map) map[k]++;
  }
  return Object.entries(map).map(([day, count]) => ({ day, count }));
}

// ─── Sparkline ────────────────────────────────────────────────────────────────

function Sparkline({ data }: { data: { day: string; count: number }[] }) {
  const max = Math.max(...data.map((d) => d.count), 1);
  const w = 280; const h = 48; const barW = w / data.length - 1;

  return (
    <svg width={w} height={h} className="overflow-visible">
      {data.map((d, i) => {
        const barH = Math.max((d.count / max) * (h - 8), d.count > 0 ? 2 : 1);
        return (
          <g key={d.day}>
            <rect
              x={i * (w / data.length)}
              y={h - barH}
              width={barW}
              height={barH}
              rx={1}
              className="fill-amber-400/60 hover:fill-amber-500 transition-colors"
            />
          </g>
        );
      })}
    </svg>
  );
}

// ─── Module card ─────────────────────────────────────────────────────────────

function ModuleCard({ mod, isRelevant }: { mod: DashboardModule; isRelevant: boolean }) {
  const bgMap: Record<ModuleStatus, string> = {
    built:   "bg-emerald-50 border-emerald-200",
    partial: "bg-amber-50/60 border-amber-200",
    planned: isRelevant ? "bg-stone-50 border-stone-200" : "bg-stone-50/40 border-stone-100",
  };
  const labelMap: Record<ModuleStatus, { text: string; color: string }> = {
    built:   { text: "Built",           color: "text-emerald-700 bg-emerald-100" },
    partial: { text: "In Progress",     color: "text-amber-700 bg-amber-100" },
    planned: { text: mod.eta ?? "Planned", color: isRelevant ? "text-stone-500 bg-stone-200" : "text-stone-300 bg-stone-100" },
  };

  return (
    <div className={`border rounded-sm p-4 ${bgMap[mod.status]} ${!isRelevant ? "opacity-50" : ""}`}>
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="flex items-center gap-2">
          <div className={`w-7 h-7 rounded-sm flex items-center justify-center flex-shrink-0 ${
            mod.status === "built" ? "bg-emerald-100" : mod.status === "partial" ? "bg-amber-100" : "bg-stone-100"
          }`}>
            <mod.icon className={`w-3.5 h-3.5 ${
              mod.status === "built" ? "text-emerald-600" : mod.status === "partial" ? "text-amber-600" : "text-stone-400"
            }`} />
          </div>
          <p className={`text-xs font-bold ${isRelevant ? "text-stone-700" : "text-stone-400"}`}>{mod.label}</p>
        </div>
        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-sm flex-shrink-0 ${labelMap[mod.status].color}`}>
          {labelMap[mod.status].text}
        </span>
      </div>
      <p className={`text-[11px] leading-snug ${isRelevant ? "text-stone-500" : "text-stone-300"}`}>{mod.description}</p>
      {mod.status === "planned" && isRelevant && (
        <div className="flex items-center gap-1 mt-2">
          <Construction className="w-3 h-3 text-stone-400" />
          <span className="text-[10px] text-stone-400">Planned for {mod.eta}</span>
        </div>
      )}
    </div>
  );
}

// ─── MAIN EXPORT ─────────────────────────────────────────────────────────────

export function ToolDashboardClient({ userId, tool, usageLogs }: Props) {
  const [copied, setCopied]     = useState(false);
  const statusCfg  = STATUS_CFG[tool.status];
  const categoryCfg = CATEGORY_CFG[tool.category] ?? { emoji: "🔧", color: "#f59e0b", bg: "#fef3c7" };
  const tags       = parseTags(tool.tags);
  const dailyUsage = buildDailyUsage(usageLogs);
  const recentUses = usageLogs.slice(0, 8);

  const copyId = () => {
    navigator.clipboard.writeText(tool.id);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Determine which modules are relevant to this tool's category
  const relevantModules = MODULES.map((m) => ({
    ...m,
    isRelevant: !m.forTypes || m.forTypes.includes(tool.category),
  }));

  const publicToolUrl = `/tools/${tool.slug}`;

  return (
    <div className="flex flex-col min-h-full">

      {/* ── Breadcrumb + Header ──────────────────────────────────────────── */}
      <div className="px-6 pt-6 pb-5 border-b border-stone-100 flex-shrink-0">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-1.5 text-xs text-stone-400 mb-4">
          <Link href={`/admin/${userId}/tools`} className="hover:text-stone-700 transition-colors flex items-center gap-1">
            <ArrowLeft className="w-3 h-3" />Tools Lab
          </Link>
          <ChevronRight className="w-3 h-3 text-stone-300" />
          <span className="text-stone-600 font-semibold">{tool.title}</span>
        </nav>

        <div className="flex items-start gap-4 flex-wrap">
          {/* Tool emoji + identity */}
          <div className="flex items-center gap-4 flex-1 min-w-0">
            <div
              className="w-14 h-14 rounded-sm flex items-center justify-center text-2xl flex-shrink-0 border border-stone-200"
              style={{ backgroundColor: `${categoryCfg.color}15` }}
            >
              {tool.emoji}
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h1 className="text-xl font-black text-stone-900 leading-tight">{tool.title}</h1>
                <span
                  className="inline-flex items-center gap-1.5 text-[11px] font-bold px-2 py-0.5 rounded-sm flex-shrink-0"
                  style={{ color: statusCfg.color, backgroundColor: statusCfg.bg }}
                >
                  <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: statusCfg.dot }} />
                  {statusCfg.label}
                </span>
                {tool.isFeatured && (
                  <span className="text-[10px] font-black bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded-sm uppercase tracking-wider">
                    Featured
                  </span>
                )}
                {tool.isPremium && (
                  <span className="text-[10px] font-black bg-purple-100 text-purple-700 px-1.5 py-0.5 rounded-sm uppercase tracking-wider flex items-center gap-1">
                    <Lock className="w-2.5 h-2.5" />Premium
                  </span>
                )}
                {tool.isInteractive && (
                  <span className="text-[10px] font-black bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded-sm uppercase tracking-wider flex items-center gap-1">
                    <Zap className="w-2.5 h-2.5" />Interactive
                  </span>
                )}
              </div>
              <p className="text-sm text-stone-500 mt-0.5">{tool.tagline}</p>
              <div className="flex items-center gap-3 mt-1.5 flex-wrap">
                <span
                  className="text-[11px] font-bold px-2 py-0.5 rounded-sm"
                  style={{ color: categoryCfg.color, backgroundColor: categoryCfg.bg }}
                >
                  {categoryCfg.emoji} {tool.category}
                </span>
                <button onClick={copyId}
                  className="flex items-center gap-1 text-[10px] text-stone-400 font-mono hover:text-stone-600 transition-colors">
                  {copied ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
                  ID: {tool.id.slice(0, 12)}…
                </button>
                <span className="text-[10px] text-stone-300">Updated {fmtDate(tool.updatedAt)}</span>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-shrink-0">
            <Link
              href={`/admin/${userId}/tools?edit=${tool.id}`}
              className="flex items-center gap-2 text-xs font-bold text-stone-600 border border-stone-200 hover:border-amber-400 hover:text-amber-700 px-3 py-2 rounded-sm transition-colors"
            >
              <Edit2 className="w-3.5 h-3.5" />Edit Tool
            </Link>
            <a
              href={publicToolUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-xs font-bold text-stone-600 border border-stone-200 hover:border-stone-400 px-3 py-2 rounded-sm transition-colors"
            >
              <ExternalLink className="w-3.5 h-3.5" />View Live
            </a>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-6">

        {/* ── "Under Development" Banner ─────────────────────────────────── */}
        <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-sm px-4 py-3.5">
          <Construction className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-black text-amber-800">Tool Dashboard Under Development</p>
            <p className="text-xs text-amber-700 mt-0.5 leading-relaxed">
              The per-tool management dashboard is being built in phases. Below you can see all planned modules for this tool. Core data and live metrics are shown now — advanced management features (prompt editor, AI config, user data, rate limits) are coming in Phase 2 and 3, tailored to each tool type.
            </p>
          </div>
        </div>

        {/* ── Quick stats ────────────────────────────────────────────────── */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { label: "Total Views",      value: tool.viewCount?.toLocaleString(),  icon: Eye,         color: "#3b82f6" },
            { label: "Total Uses",       value: tool.useCount?.toLocaleString(),   icon: Zap,         color: "#10b981" },
            { label: "Avg Rating",       value: tool.ratingCount > 0 ? `${tool.rating.toFixed(1)} ★` : "—", icon: Star, color: "#f59e0b" },
            { label: "Ratings Count",    value: tool.ratingCount.toLocaleString(), icon: Users,      color: "#8b5cf6" },
          ].map((s) => (
            <div key={s.label} className="bg-white border border-stone-100 rounded-sm p-4">
              <s.icon className="w-4 h-4 mb-2" style={{ color: s.color }} />
              <p className="text-xl font-black text-stone-900">{s.value}</p>
              <p className="text-[11px] font-semibold text-stone-400 mt-0.5">{s.label}</p>
            </div>
          ))}
        </div>

        {/* ── Usage sparkline (last 30d) ─────────────────────────────────── */}
        <div className="bg-white border border-stone-100 rounded-sm p-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="text-sm font-black text-stone-800">Usage — last 30 days</p>
              <p className="text-xs text-stone-400 mt-0.5">
                {usageLogs.length} logged use{usageLogs.length !== 1 ? "s" : ""} · live data when DB connected
              </p>
            </div>
            <span className="text-[10px] text-stone-400 bg-stone-100 px-2 py-1 rounded-sm font-semibold">
              PREVIEW
            </span>
          </div>
          {usageLogs.length > 0 ? (
            <Sparkline data={dailyUsage} />
          ) : (
            <div className="h-12 flex items-center justify-center border border-dashed border-stone-200 rounded-sm">
              <p className="text-xs text-stone-300">No usage data yet</p>
            </div>
          )}
          {recentUses.length > 0 && (
            <div className="mt-4 border-t border-stone-50 pt-3 space-y-1">
              <p className="text-[10px] font-bold text-stone-400 uppercase tracking-wider mb-2">Recent uses</p>
              {recentUses.map((log) => (
                <div key={log.id} className="flex items-center gap-3 text-[11px] text-stone-500">
                  <span className="font-mono text-stone-300">{new Date(log.usedAt).toLocaleString("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>
                  <span className="text-stone-400">{log.userId ? "Auth user" : "Anonymous"}</span>
                  {log.sessionId && <span className="font-mono text-stone-300 text-[10px]">{log.sessionId.slice(0, 8)}…</span>}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* ── Tool details ───────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Left: core metadata */}
          <div className="bg-white border border-stone-100 rounded-sm p-5">
            <p className="text-xs font-black text-stone-400 uppercase tracking-wider mb-4">Tool Details</p>
            <div className="space-y-3">
              {[
                { label: "Title",          value: tool.title },
                { label: "Slug",           value: tool.slug, mono: true },
                { label: "Category",       value: `${categoryCfg.emoji} ${tool.category}` },
                { label: "Status",         value: statusCfg.label },
                { label: "Interactive",    value: tool.isInteractive ? "Yes" : "No" },
                { label: "Component key",  value: tool.componentKey ?? "—", mono: true },
                { label: "Premium",        value: tool.isPremium ? "Yes" : "No" },
                { label: "Featured",       value: tool.isFeatured ? "Yes" : "No" },
                { label: "Created",        value: fmtDate(tool.createdAt) },
              ].map((row: { label: string; value: string; mono?: boolean }) => (
                <div key={row.label} className="flex gap-3">
                  <span className="text-[11px] text-stone-400 w-28 flex-shrink-0">{row.label}</span>
                  <span className={`text-[11px] text-stone-700 font-semibold ${row.mono ? "font-mono" : ""}`}>{row.value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Right: description + tags */}
          <div className="bg-white border border-stone-100 rounded-sm p-5">
            <p className="text-xs font-black text-stone-400 uppercase tracking-wider mb-4">Description & Tags</p>
            <p className="text-sm text-stone-600 leading-relaxed mb-4">{tool.description}</p>
            <div className="flex flex-wrap gap-1.5">
              {tags.map((t) => (
                <span key={t} className="text-[11px] font-semibold bg-stone-100 text-stone-600 px-2.5 py-1 rounded-sm">{t}</span>
              ))}
              {tags.length === 0 && <span className="text-xs text-stone-300">No tags added</span>}
            </div>
            {tool.coverImage && (
              <div className="mt-4 pt-4 border-t border-stone-100">
                <p className="text-[10px] font-bold text-stone-400 uppercase tracking-wider mb-2">Cover Image</p>
                <a href={tool.coverImage} target="_blank" rel="noopener noreferrer"
                  className="text-[11px] text-blue-600 hover:underline break-all">{tool.coverImage}</a>
              </div>
            )}
          </div>
        </div>

        {/* ── Dashboard modules roadmap ─────────────────────────────────── */}
        <div>
          <div className="flex items-center gap-3 mb-4">
            <p className="text-sm font-black text-stone-800">Dashboard Modules</p>
            <span className="text-[10px] text-stone-400 bg-stone-100 px-2 py-1 rounded-sm font-semibold">
              {relevantModules.filter((m) => m.status === "built").length} built · {relevantModules.filter((m) => m.isRelevant && m.status !== "built").length} planned
            </span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {relevantModules
              .sort((a, b) => {
                // Sort: built first, then by relevance
                if (a.status === "built" && b.status !== "built") return -1;
                if (b.status === "built" && a.status !== "built") return 1;
                if (a.isRelevant && !b.isRelevant) return -1;
                if (b.isRelevant && !a.isRelevant) return 1;
                return 0;
              })
              .map((mod) => (
                <ModuleCard key={mod.id} mod={mod} isRelevant={mod.isRelevant} />
              ))}
          </div>
        </div>

        {/* ── Public tool link ──────────────────────────────────────────── */}
        <div className="bg-white border border-stone-100 rounded-sm p-5">
          <p className="text-xs font-black text-stone-400 uppercase tracking-wider mb-3">Public URL</p>
          <div className="flex items-center gap-3">
            <code className="flex-1 text-xs font-mono text-stone-600 bg-stone-50 border border-stone-200 px-3 py-2 rounded-sm truncate">
              https://isaacpaha.com/tools/{tool.slug}
            </code>
            <a
              href={publicToolUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-xs font-bold text-amber-700 bg-amber-50 border border-amber-200 hover:bg-amber-100 px-3 py-2 rounded-sm transition-colors flex-shrink-0"
            >
              <ExternalLink className="w-3.5 h-3.5" />Open
            </a>
          </div>
        </div>

      </div>
    </div>
  );
}