// =============================================================================
// TOOLS TERMS PAGE
// app/tools-terms/page.tsx
//
// Full, comprehensive tools terms page.
// Server component with complete SEO metadata.
// =============================================================================

import type { Metadata } from "next";
import Link from "next/link";

// ── SEO ───────────────────────────────────────────────────────────────────────
export const metadata: Metadata = {
  title: "AI Tools Terms & Conditions | Isaac Paha",
  description:
    "Full terms and conditions governing all AI tools, token usage, data privacy, and fair use on isaacpaha.com. Read before using.",
  alternates: { canonical: "https://www.isaacpaha.com/tools-terms" },
  robots: { index: true, follow: true },
};

// ── Data ──────────────────────────────────────────────────────────────────────
const LAST_UPDATED  = "1 January 2026";
const EFFECTIVE     = "1 January 2026";
const OPERATOR      = "Isaac Paha / iPaha Ltd";
const CONTACT_EMAIL = "legal@ipahait.com";
const PLATFORM_URL  = "https://www.isaacpaha.com";
const COMPANY_URL   = "https://ipahait.com";

const SECTIONS = [
  {
    id:    "1",
    title: "Introduction & Purpose",
    content: `
These Terms & Conditions ("Terms") govern your use of all AI-powered tools, utilities, 
generators, and related services ("Tools") available on isaacpaha.com ("the Platform"), 
operated by Isaac Paha and iPaha Ltd ("we", "us", "our").

These Tools were built with a singular purpose: to help you get things done. Whether 
you're navigating a career change, writing something important, learning a new skill, 
or handling life admin — these tools are here to make your life easier, faster, and 
more effective.

By accessing or using any Tool on this Platform, you confirm that you have read, 
understood, and agree to be bound by these Terms in full. If you do not agree, you 
must not use any Tool.
    `.trim(),
  },
  {
    id:    "2",
    title: "Eligibility & Age Requirements",
    content: `
2.1 You must be at least 13 years of age, or the age of digital consent in your 
jurisdiction (whichever is higher), to use any Tool on this Platform.

2.2 Users under 18 should use these Tools with parental or guardian supervision, 
particularly for tools that generate or process personal information.

2.3 By using the Tools, you represent and warrant that:
    (a) You are of legal age in your jurisdiction to use digital services;
    (b) You are not accessing the Platform from a jurisdiction where such services 
        are prohibited;
    (c) You are acting on your own behalf and not on behalf of any third party 
        without proper authorisation.

2.4 We reserve the right to request age verification at any time. Failure to provide 
satisfactory verification may result in account suspension.
    `.trim(),
  },
  {
    id:    "3",
    title: "Nature of AI Tools",
    content: `
3.1 AI-GENERATED CONTENT: These Tools use artificial intelligence models to generate 
responses, suggestions, code, text, and other outputs based on your inputs. All outputs 
are generated by AI and may contain errors, inaccuracies, biases, or hallucinated 
information.

3.2 NO GUARANTEE OF ACCURACY: You acknowledge that AI outputs are provided "as is" and 
may not be suitable for your specific circumstances. You are solely responsible for 
verifying any critical information before relying on it.

3.3 NOT PROFESSIONAL ADVICE: The Tools are not a substitute for professional advice 
in legal, financial, medical, psychological, or other regulated fields. Always consult 
a qualified professional for matters that could impact your life, health, finances, 
or legal standing.

3.4 LIMITATIONS: AI models have inherent limitations including:
    (a) Knowledge cutoffs (may not include recent information);
    (b) Potential for factual errors or hallucinations;
    (c) Biases present in training data;
    (d) Inability to reason about real-time events;
    (e) Variable output quality based on input phrasing.

3.5 These Tools should be used as assistants, not replacements, for human judgment 
and critical thinking.
    `.trim(),
  },
  {
    id:    "4",
    title: "Token System & Premium Features",
    content: `
4.1 VIRTUAL TOKENS: Tokens are virtual credits used to access premium features and 
higher-quality AI models. Tokens have no inherent real-world monetary value and are 
not currency, securities, investments, or financial instruments.

4.2 FREE TIER: Most Tools offer free usage tiers with rate limits. Free tier users 
may experience:
    (a) Slower response times during peak hours;
    (b) Access to standard AI models (not premium);
    (c) Rate limits (number of requests per hour/day);
    (d) Basic feature sets.

4.3 PREMIUM ACCESS: Premium features require token expenditure. Token costs per use 
are displayed before you initiate a premium request.

4.4 EARNING TOKENS: Tokens may be earned through:
    (a) Account creation and verification;
    (b) Daily logins and activity streaks;
    (c) Referrals of new users;
    (d) Platform events and promotions;
    (e) Providing helpful feedback.

4.5 PURCHASING TOKENS: Token packages may be available for purchase. All token 
purchases are final and non-refundable except where required by consumer protection law.

4.6 TOKEN EXPIRY: Tokens may expire if an account remains inactive for 12 consecutive 
months. Users will be notified by email 30 days before expiry.

4.7 NO CASH VALUE: Tokens cannot be redeemed for cash, transferred between accounts, 
or exchanged for anything outside the Platform. Any cash-out feature, if introduced, 
would be at our sole discretion and subject to separate terms.

4.8 TOKEN LOSS: We accept no responsibility for token loss due to:
    (a) Account compromise (you are responsible for account security);
    (b) Technical errors or platform downtime;
    (c) Abuse of the token system;
    (d) Account termination for Terms violations.
    `.trim(),
  },
  {
    id:    "5",
    title: "Data Privacy & Processing",
    content: `
5.1 INPUT DATA: When you use these Tools, your inputs (text, prompts, uploaded files) 
are processed to generate outputs. We may store inputs to:
    (a) Improve Tool quality and performance;
    (b) Detect and prevent abuse;
    (c) Comply with legal obligations;
    (d) Debug and fix technical issues.

5.2 SENSITIVE INFORMATION: You must not submit sensitive personal information 
(health data, financial account numbers, government IDs, etc.) unless explicitly 
required by the Tool and marked as secure. If you accidentally submit sensitive 
information, please contact us immediately at ${CONTACT_EMAIL}.

5.3 DATA RETENTION: Inputs and outputs may be retained for up to 90 days for 
quality improvement and abuse prevention. Anonymized data may be retained longer 
for model training and research.

5.4 NO DATA SELLING: We do not sell your personal data or input content to third 
parties. We do not train public AI models on your data without your explicit consent.

5.5 THIRD-PARTY AI PROVIDERS: Some Tools may use third-party AI providers (such as 
OpenAI, Anthropic, etc.). Your inputs may be subject to those providers' data 
handling policies. We select providers with strong privacy commitments but cannot 
control their internal data practices.

5.6 For complete details, refer to our Privacy Policy at ${PLATFORM_URL}/privacy.
    `.trim(),
  },
  {
    id:    "6",
    title: "Acceptable Use & Prohibited Conduct",
    content: `
6.1 You agree to use these Tools responsibly, ethically, and in accordance with 
these Terms and applicable law.

6.2 PROHIBITED USES include but are not limited to:
    (a) Generating illegal content, hate speech, harassment, or harmful material;
    (b) Creating impersonation, fraud, or deceptive content;
    (c) Attempting to extract, reverse-engineer, or replicate the AI models;
    (d) Using automated scripts, bots, or scrapers to bypass rate limits;
    (e) Exploiting bugs, glitches, or vulnerabilities for unfair advantage;
    (f) Creating multiple accounts to circumvent token limits or bans;
    (g) Using Tools to generate content for regulated activities without proper 
        licensing (legal, medical, financial advice);
    (h) Uploading malicious code, viruses, or harmful files;
    (i) Using Tools to harass, stalk, or threaten others;
    (j) Circumventing content moderation or safety systems.

6.3 RATE LIMITS: We enforce rate limits to ensure fair access for all users. 
Exceeding these limits may result in temporary throttling or permanent suspension.

6.4 CONSEQUENCES: Violation of these terms may result in:
    (a) Temporary suspension of account access;
    (b) Permanent ban from the Platform;
    (c) Forfeiture of all token balances;
    (d) Legal action where appropriate.

6.5 REPORTING: If you discover abuse or prohibited content, please report to 
${CONTACT_EMAIL} with relevant evidence.
    `.trim(),
  },
  {
    id:    "7",
    title: "Intellectual Property",
    content: `
7.1 OUR IP: All Tool interfaces, code, designs, branding, and underlying technology 
are the exclusive intellectual property of Isaac Paha and iPaha Ltd.

7.2 OUTPUT OWNERSHIP: Subject to your compliance with these Terms, you own the 
outputs generated by the Tools from your inputs. However:
    (a) Outputs may be similar or identical to outputs generated for other users;
    (b) We may use aggregated, anonymized outputs to improve the Tools;
    (c) Outputs may incorporate underlying AI model knowledge that is not exclusively yours.

7.3 YOUR INPUTS: You retain ownership of your inputs. You grant us a license to 
process your inputs to provide and improve the Tools.

7.4 RESTRICTIONS: You may not:
    (a) Reverse-engineer, decompile, or extract the Tools;
    (b) Use outputs to train competing AI models;
    (c) Resell, redistribute, or commercialize outputs without transformation 
        into your own original work;
    (d) Claim ownership of the Tools themselves.
    `.trim(),
  },
  {
    id:    "8",
    title: "Limitation of Liability",
    content: `
8.1 NO LIABILITY FOR OUTPUTS: Isaac Paha and iPaha Ltd accept no responsibility for:
    (a) Errors, inaccuracies, or harmful outputs generated by AI;
    (b) Decisions made based on AI-generated content;
    (c) Loss of tokens due to usage, technical errors, or account issues;
    (d) Business losses, lost profits, or missed opportunities;
    (e) Any indirect, consequential, special, or punitive damages.

8.2 NO WARRANTY: All Tools are provided "as is" and "as available" without any 
warranty of any kind, express or implied, including warranties of merchantability, 
fitness for a particular purpose, or non-infringement.

8.3 AVAILABILITY: We do not guarantee uninterrupted or error-free access to the 
Tools. Scheduled and unscheduled maintenance may affect availability.

8.4 THIRD-PARTY PROVIDERS: We are not responsible for the performance, availability, 
or data practices of third-party AI providers, hosting services, or other dependencies.

8.5 MAXIMUM LIABILITY: To the maximum extent permitted by applicable law, our total 
aggregate liability to you under these Terms shall not exceed the total amount of 
tokens you have purchased in the 12 months preceding the claim, or £50, whichever 
is greater.

8.6 CRITICAL DECISIONS: You acknowledge that these Tools are not designed for use 
in situations where failure could result in death, personal injury, or severe 
environmental damage. Do not use for critical applications.
    `.trim(),
  },
  {
    id:    "9",
    title: "Account Security",
    content: `
9.1 You are responsible for maintaining the security of your account credentials 
and for all activity that occurs under your account.

9.2 If you suspect unauthorised access, immediately change your password and 
contact us at ${CONTACT_EMAIL}.

9.3 We may suspend or terminate accounts that:
    (a) Violate these Terms;
    (b) Are compromised or pose security risks;
    (c) Remain inactive for 24 months;
    (d) Are associated with fraudulent or abusive behaviour.

9.4 TOKEN SECURITY: Token balances are digital records. We are not liable for 
token loss due to account compromise where you failed to maintain security.
    `.trim(),
  },
  {
    id:    "10",
    title: "Responsible Use & Wellbeing",
    content: `
10.1 These Tools are designed to help, not harm. We encourage you to:
    (a) Use Tools to augment your own skills, not replace them;
    (b) Verify critical information independently;
    (c) Take breaks and maintain healthy digital habits;
    (d) Respect that these are shared resources with limited capacity.

10.2 If you find yourself relying excessively on these Tools for emotional support, 
decision-making, or validation, please consider speaking with a qualified professional 
who can provide appropriate support.

10.3 Resources for digital wellbeing:
    — Mind (mental health): www.mind.org.uk / 0300 123 3393
    — Samaritans: www.samaritans.org / 116 123 (UK)
    — International support: www.befrienders.org

10.4 These Tools exist to make your life easier. If they're causing stress or 
anxiety, step back. They'll be here when you need them.
    `.trim(),
  },
  {
    id:    "11",
    title: "Modifications to Terms",
    content: `
11.1 We reserve the right to modify these Terms at any time. Material changes will 
be communicated via the Platform interface and/or email at least 14 days before 
taking effect for active users.

11.2 Your continued use of the Tools after changes take effect constitutes acceptance 
of the revised Terms. If you do not accept the changes, you must cease using the Tools.

11.3 We may add, modify, or remove Tools and features at any time without liability. 
We will endeavour to provide reasonable notice for significant changes.
    `.trim(),
  },
  {
    id:    "12",
    title: "Governing Law & Dispute Resolution",
    content: `
12.1 These Terms and any dispute arising from them shall be governed by and construed 
in accordance with the laws of England and Wales.

12.2 The parties agree to submit to the exclusive jurisdiction of the courts of 
England and Wales for the resolution of any disputes, without prejudice to any 
mandatory consumer protection rights you may have in your local jurisdiction.

12.3 Before commencing any legal proceedings, you agree to first notify us in writing 
at ${CONTACT_EMAIL} and give us 30 days to attempt to resolve the matter amicably.

12.4 Nothing in these Terms shall exclude or limit any statutory rights you may have 
as a consumer that cannot be excluded or limited under applicable law.
    `.trim(),
  },
  {
    id:    "13",
    title: "Contact & Operator Information",
    content: `
Operator:          ${OPERATOR}
Platform:          ${PLATFORM_URL}
Company website:   ${COMPANY_URL}
Legal enquiries:   ${CONTACT_EMAIL}
General support:   support@ipahait.com
Tool feedback:     feedback@ipahait.com

For questions, bug reports, feature requests, or concerns regarding these Terms, 
please contact us. We aim to respond to all legal and compliance enquiries within 
5 business days.

Isaac Paha built these tools because he believes technology should work for people, 
not the other way around. Every tool was created to solve real problems faced by 
real people — founders, job seekers, students, writers, parents. Use them well, 
and if something's missing, let me know. That's how this grows.
    `.trim(),
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COMPONENTS
// ─────────────────────────────────────────────────────────────────────────────

function AmbientBg() {
  return (
    <div className="absolute inset-0 pointer-events-none overflow-hidden">
      {/* Grid */}
      <div className="absolute inset-0" style={{
        backgroundImage: "linear-gradient(#e7e5e4 1px,transparent 1px),linear-gradient(90deg,#e7e5e4 1px,transparent 1px)",
        backgroundSize: "52px 52px",
        opacity: 0.2,
      }} />
      {/* Amber nebula */}
      <div className="absolute -top-40 right-0 w-[600px] h-[600px] rounded-full opacity-30"
        style={{ background: "radial-gradient(circle,rgba(245,158,11,0.04) 0%,transparent 65%)", filter: "blur(60px)" }} />
      {/* Purple nebula */}
      <div className="absolute top-1/3 -left-20 w-[500px] h-[500px] rounded-full opacity-20"
        style={{ background: "radial-gradient(circle,rgba(168,85,247,0.03) 0%,transparent 65%)", filter: "blur(50px)" }} />
    </div>
  );
}

interface SectionProps {
  id:      string;
  title:   string;
  content: string;
}

function Section({ id, title, content }: SectionProps) {
  const paragraphs = content.split("\n\n").filter(Boolean);
  return (
    <section id={`section-${id}`} className="scroll-mt-8">
      <div className="flex items-start gap-4 mb-4">
        <div className="flex-shrink-0 w-8 h-8 rounded-xs flex items-center justify-center mt-0.5"
          style={{
            background: "#fef3c7",
            border: "1px solid #fed7aa",
          }}>
          <span className="text-[11px] font-black" style={{ color: "#d97706" }}>{id}</span>
        </div>
        <h2 className="text-lg font-black text-gray-900" style={{ letterSpacing: "-0.03em", lineHeight: 1.25 }}>
          {title}
        </h2>
      </div>

      <div className="ml-12 space-y-3">
        {paragraphs.map((para, i) => {
          const isSublist = para.trim().startsWith("(a)") || para.trim().startsWith("    (a)");
          if (isSublist) {
            const lines = para.split("\n").filter(Boolean);
            return (
              <div key={i} className="space-y-1.5">
                {lines.map((line, j) => {
                  const trimmed = line.trim();
                  const isItem  = /^\([a-z]\)/.test(trimmed);
                  return (
                    <div key={j} className="flex items-start gap-2.5">
                      {isItem && (
                        <div className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0"
                          style={{ background: "#f59e0b" }} />
                      )}
                      <p className="text-sm leading-relaxed"
                        style={{ color: "#78716c", marginLeft: isItem ? 0 : "1.125rem" }}>
                        {isItem ? trimmed.replace(/^\([a-z]\)\s*/, "") : trimmed}
                      </p>
                    </div>
                  );
                })}
              </div>
            );
          }
          return (
            <p key={i} className="text-sm leading-relaxed" style={{ color: "#78716c" }}>
              {para}
            </p>
          );
        })}
      </div>

      <div className="mt-8 ml-12 h-px" style={{ background: "linear-gradient(90deg,#e7e5e4,transparent)" }} />
    </section>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGE
// ─────────────────────────────────────────────────────────────────────────────

export default function ToolsTermsPage() {
  return (
    <div className="min-h-screen relative" style={{ background: "#fafaf9", fontFamily: "'Sora', system-ui, sans-serif" }}>
      <AmbientBg />

      <div className="absolute top-0 left-0 right-0 h-[2.5px]"
        style={{ background: "linear-gradient(90deg,transparent,#f59e0b 30%,#a855f7 70%,transparent)" }} />

      <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">

        <div className="mb-12">
          <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest mb-6"
            style={{ color: "#a8a29e" }}>
            <Link href="/" style={{ color: "#a8a29e", textDecoration: "none" }}>Home</Link>
            <span>/</span>
            <Link href="/tools" style={{ color: "#a8a29e", textDecoration: "none" }}>Tools</Link>
            <span>/</span>
            <span style={{ color: "#f59e0b" }}>Terms</span>
          </div>

          <div className="flex items-center gap-3 mb-4">
            <span className="text-[9px] font-black tracking-[0.2em] uppercase px-3 py-1 rounded-xs"
              style={{
                background: "#fef3c7",
                border: "1px solid #fed7aa",
                color: "#d97706",
              }}>
              Legal
            </span>
            <span className="text-[10px]" style={{ color: "#a8a29e" }}>
              Last updated: {LAST_UPDATED} · Effective: {EFFECTIVE}
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl font-black text-gray-900 mb-4"
            style={{ letterSpacing: "-0.05em", lineHeight: 1.05 }}>
            AI Tools<br />
            <span style={{ background: "linear-gradient(90deg,#f59e0b,#a855f7)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              Terms & Conditions
            </span>
          </h1>

          <div className="rounded-xs p-5 mt-6"
            style={{
              background: "linear-gradient(135deg,#fffbeb 0%,#fef3c7 100%)",
              border: "1px solid #fed7aa",
            }}>
            <p className="text-sm leading-relaxed" style={{ color: "#78716c" }}>
              <span className="font-black text-gray-900">A note from Isaac: </span>
              I built these tools because I wanted things that actually help — not AI slop 
              or overpriced SaaS. Career pivots, writing blocks, learning something new — 
              these are the moments that matter. I hope these tools save you time, spark 
              ideas, and make your life a little easier. Use them well. And if something 
              doesn't work right or could be better, tell me. ❤️
            </p>
          </div>
        </div>

        <nav className="rounded-xs p-5 mb-10"
          style={{ background: "#ffffff", border: "1px solid #e7e5e4" }}>
          <p className="text-[9px] uppercase tracking-[0.2em] font-black mb-4"
            style={{ color: "#a8a29e" }}>
            Contents
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-y-2 gap-x-6">
            {SECTIONS.map(s => (
              <a
                key={s.id}
                href={`#section-${s.id}`}
                className="flex items-center gap-2 group"
                style={{ textDecoration: "none" }}>
                <span className="text-[10px] font-black w-5 flex-shrink-0"
                  style={{ color: "#f59e0b" }}>
                  {s.id}.
                </span>
                <span className="text-[11px] font-semibold transition-colors"
                  style={{ color: "#78716c" }}>
                  {s.title}
                </span>
              </a>
            ))}
          </div>
        </nav>

        <div className="space-y-10">
          {SECTIONS.map(s => (
            <Section key={s.id} id={s.id} title={s.title} content={s.content} />
          ))}
        </div>

        <div className="mt-14 pt-8" style={{ borderTop: "1px solid #e7e5e4" }}>

          <div className="rounded-xs p-5 mb-8"
            style={{ background: "#f5f5f4", border: "1px solid #e7e5e4" }}>
            <p className="text-[9px] uppercase tracking-[0.2em] font-black mb-3"
              style={{ color: "#a8a29e" }}>
              Operator Details
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px]"
              style={{ color: "#78716c" }}>
              <div><span style={{ color: "#a8a29e" }}>Operator:</span> {OPERATOR}</div>
              <div><span style={{ color: "#a8a29e" }}>Platform:</span>{" "}
                <a href={PLATFORM_URL} style={{ color: "#f59e0b" }}>{PLATFORM_URL}</a>
              </div>
              <div><span style={{ color: "#a8a29e" }}>Legal email:</span>{" "}
                <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#f59e0b" }}>{CONTACT_EMAIL}</a>
              </div>
              <div><span style={{ color: "#a8a29e" }}>Company:</span>{" "}
                <a href={COMPANY_URL} style={{ color: "#f59e0b" }}>{COMPANY_URL}</a>
              </div>
            </div>
          </div>

          <div className="text-center space-y-2">
            <p className="text-2xl">⚡</p>
            <p className="text-sm font-black text-gray-900" style={{ letterSpacing: "-0.02em" }}>
              Tools that actually help.
            </p>
            <p className="text-xs" style={{ color: "#a8a29e", lineHeight: 1.7 }}>
              Built for the moments that matter. Go get things done.
            </p>
            <p className="text-[10px] mt-4" style={{ color: "#d6d3d1" }}>
              © {new Date().getFullYear()} Isaac Paha / iPaha Ltd · All rights reserved ·{" "}
              <Link href="/privacy" style={{ color: "#a8a29e", textDecoration: "underline" }}>
                Privacy Policy
              </Link>
              {" "}·{" "}
              <Link href="/tools" style={{ color: "#a8a29e", textDecoration: "underline" }}>
                Back to Tools
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}